@BaseUrl = http://localhost:8080
@Token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhY2NvdW50SWQiOiI4M2U0MDY4My1lYjVmLTQyNWQtOTRjOC1iMDQ2NjBlNWUxNDIiLCJpYXQiOjE3MzUyNjAwMDgsImV4cCI6MTczNTI2NzIwOH0.WNhZE0YuaJ6yhTsmS5JLHN_uqd7zs9x3rqCwe6QQiCs

# @name create_account
POST {{BaseUrl}}/signup
Content-Type: application/json

{
  "firstName": "John",
  "lastName": "Doe",
  "email": "john.doe@example.com",
  "password": "John@123"
}

###

# @name create_account
POST {{BaseUrl}}/signup
Content-Type: application/json

{
  "firstName": "Jane",
  "lastName": "Smith",
  "email": "jane.smith@example.com",
  "password": "Jane@123"
}

###

# @name authentication
POST {{BaseUrl}}/login
Content-Type: application/json

{
  "email": "john.doe@example.com",
  "password": "John@123"
}

###

# @name authentication
POST {{BaseUrl}}/login
Content-Type: application/json

{
  "email": "jane.smith@example.com",
  "password": "Jane@123"
}

###

# @name create_event
POST {{BaseUrl}}/events
Authorization: Bearer {{Token}}
Content-Type: application/json

{
  "description": "Event 1",
  "startedAt": "2025-12-21T00:00:00",
  "finishedAt": "2025-12-22T00:00:00"
}

###

# @name edit_event
PUT {{BaseUrl}}/events/488b283c-e1a9-46e1-9d35-3ec7ed08205d
Authorization: Bearer {{Token}}
Content-Type: application/json

{
  "description": "New description",
  "startedAt": "2025-12-30T01:00:00",
  "finishedAt": "2025-12-31T05:12:00"
}

###

# @name remove_event
DELETE {{BaseUrl}}/events/488b283c-e1a9-46e1-9d35-3ec7ed08205d
Authorization: Bearer {{Token}}
Content-Type: application/json

###

# @name get_events

GET {{BaseUrl}}/events
Authorization: Bearer {{Token}}
Content-Type: application/json

###

# @name invite

POST {{BaseUrl}}/events/f431e44b-3493-406e-bede-96cbc70d589a/invite
Authorization: Bearer {{Token}}
Content-Type: application/json

{
  "guestId": "83e40683-eb5f-425d-94c8-b04660e5e142"
}

###

# @name get_invitees

GET {{BaseUrl}}/invitees
Authorization: Bearer {{Token}}
Content-Type: application/json

###

# @name accept_invite

PATCH {{BaseUrl}}/invitees/c514e884-735b-4e87-a513-623812dee6eb/accept
Authorization: Bearer {{Token}}
Content-Type: application/json

###

# @name decline_invite

PATCH {{BaseUrl}}/invitees/:inviteeId/decline
Authorization: Bearer {{Token}}
Content-Type: application/json
