@BaseUrl = http://localhost:8080

# @name create_account
POST {{BaseUrl}}/signup
Content-Type: application/json

{
  "firstName": "John",
  "lastName": "Doe",
  "email": "john.doe@example.com",
  "password": "John@123"
}

###

# @name authentication
POST {{BaseUrl}}/login
Content-Type: application/json

{
  "email": "john.doe@example.com",
  "password": "John@123"
}