@BaseUrl = http://localhost:8080
@Token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhY2NvdW50SWQiOiJhMGMwYWRkMC1hNjYwLTRmNzctYmRmNS1kMjVjMDFiNDU5MWMiLCJpYXQiOjE3MzUzMzYzOTksImV4cCI6MTczNTM0MzU5OX0.tGSRpp21i-9FLLzFi_7o4qpuL9dYwxbvGzI8t-gy5qI

# @name create_account
POST {{BaseUrl}}/signup
Content-Type: application/json

{
  "firstName": "John",
  "lastName": "Doe",
  "email": "john.doe@example.com",
  "password": "John@123"
}

###

# @name create_account
POST {{BaseUrl}}/signup
Content-Type: application/json

{
  "firstName": "Jane",
  "lastName": "Smith",
  "email": "jane.smith@example.com",
  "password": "Jane@123"
}

###

# @name authentication
POST {{BaseUrl}}/login
Content-Type: application/json

{
  "email": "john.doe@example.com",
  "password": "John@123"
}

###

# @name authentication
POST {{BaseUrl}}/login
Content-Type: application/json

{
  "email": "jane.smith@example.com",
  "password": "Jane@123"
}

###

# @name create_event
POST {{BaseUrl}}/events
Authorization: Bearer {{Token}}
Content-Type: application/json

{
  "description": "Event 2",
  "startedAt": "2025-12-21T00:00:00",
  "finishedAt": "2025-12-22T00:00:00"
}

###

# @name edit_event
PUT {{BaseUrl}}/events/71b9d202-0b4b-4742-acfd-a67a08c558c8
Authorization: Bearer {{Token}}
Content-Type: application/json

{
  "description": "New description",
  "startedAt": "2025-12-30T01:00:00",
  "finishedAt": "2025-12-31T05:12:00"
}

###

# @name remove_event
DELETE {{BaseUrl}}/events/71b9d202-0b4b-4742-acfd-a67a08c558c8
Authorization: Bearer {{Token}}
Content-Type: application/json

###

# @name get_events

GET {{BaseUrl}}/events
Authorization: Bearer {{Token}}
Content-Type: application/json

###

# @name invite

POST {{BaseUrl}}/events/f77a52ae-a6aa-4a47-96fa-9f63c2e5ab32/invite
Authorization: Bearer {{Token}}
Content-Type: application/json

{
  "guestId": "a0c0add0-a660-4f77-bdf5-d25c01b4591c"
}

###

# @name get_invitees

GET {{BaseUrl}}/invitees
Authorization: Bearer {{Token}}
Content-Type: application/json

###

# @name accept_invite

PATCH {{BaseUrl}}/invitees/92bb7616-1b4c-464d-a51a-25c6289ea46e/accept
Authorization: Bearer {{Token}}
Content-Type: application/json

###

# @name decline_invite

PATCH {{BaseUrl}}/invitees/:inviteeId/decline
Authorization: Bearer {{Token}}
Content-Type: application/json
