services:
  api:
    container_name: api
    build:
      context: ./
    ports:
      - 8080:8080
    depends_on:
      postgres:
        condition: service_started
    env_file:
      - ./.env
    networks:
      - api_backend-network

  postgres:
    image: postgres:14.3-alpine
    container_name: postgres
    environment:
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: app
    ports:
      - 5432:5432
    networks:
      - api_backend-network
    volumes:
      - ./resources/schema.sql:/docker-entrypoint-initdb.d/init.sql

networks:
  api_backend-network:
    driver: bridge
